# Generated by Django 5.0.7 on 2024-07-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='fac_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='fac_password',
            new_name='password',
        ),
    ]
