# Generated by Django 5.0.7 on 2024-07-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fac_email_faculty_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='email',
            new_name='femail',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='password',
            new_name='fpassword',
        ),
    ]
