# Generated by Django 5.0.7 on 2024-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_email_faculty_femail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='name',
        ),
    ]
