# Generated by Django 5.0.6 on 2024-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_policyholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
