# Generated by Django 5.0.6 on 2024-07-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_policyholder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='insurance_applications',
            field=models.ManyToManyField(to='myapp.insuranceapplication'),
        ),
    ]
