# Generated by Django 5.0.6 on 2024-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_password_customer_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
