# Generated by Django 5.0.6 on 2024-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_lifeinsurancepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsurancepolicy',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='policy_pictures'),
        ),
    ]
